In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **Load data from JSON to pandas**

In [ ]:
business = pd.read_json('/content/drive/MyDrive/MiniProject1_B10/yelp_academic_dataset_business.json',lines= True)
business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [ ]:
checkin = pd.read_json('/content/drive/MyDrive/MiniProject1_B10/yelp_academic_dataset_checkin.json',lines= True)
checkin['date'] = checkin['date'].astype(str).str.split(',')
checkin = checkin.explode('date')
checkin.head()

              business_id                  date
0  ---kPU91CF4Lq2-WlRu9Lw   2020-03-13 21:10:56
0  ---kPU91CF4Lq2-WlRu9Lw   2020-06-02 22:18:06
0  ---kPU91CF4Lq2-WlRu9Lw   2020-07-24 22:42:27
0  ---kPU91CF4Lq2-WlRu9Lw   2020-10-24 21:36:13
0  ---kPU91CF4Lq2-WlRu9Lw   2020-12-09 21:23:33

In [ ]:
review = pd.read_json('/content/drive/MyDrive/MiniProject1_B10/yelp_academic_dataset_review.json',lines=True, chunksize = 10000)
review = pd.concat(review)

In [ ]:
review.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [ ]:
tip = pd.read_json('/content/drive/MyDrive/MiniProject1_B10/yelp_academic_dataset_tip.json',lines= True)
tip.head()

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0

In [ ]:
user = pd.read_json('/content/drive/MyDrive/MiniProject1_B10/yelp_academic_dataset_user.json',lines= True, chunksize = 10000)
user = pd.concat(user)
user.head()

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0

## **Database** **Modelling**

**Creating a separate entity for 'Category', 'Attribute' & 'Hours' from the 'Business' data**

In [ ]:
categories_series = business['categories']
categories = pd.DataFrame({'category': categories_series.values})
#categories['category'] = categories['category'].astype(str).str.split(',')
#categories = categories.explode('category')
categories['C_id'] = ['C{}'.format(i) for i in range(1, len(categories) + 1)]
categories['business_id'] = business['business_id']
categories.head(20)

,category,C_id,business_id
0,"Doctors, Traditional Chinese Medicine, Naturop...",C1,Pns2l4eNsfO8kk83dixA6A
1,"Shipping Centers, Local Services, Notaries, Ma...",C2,mpf3x-BjTdTEA3yCZrAYPw
2,"Department Stores, Shopping, Fashion, Home & G...",C3,tUFrWirKiKi_TAnsVWINQQ
3,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",C4,MTSW4McQd7CbVtyjqoe9mw
4,"Brewpubs, Breweries, Food",C5,mWMc6_wTdE0EUBKIGXDVfA
5,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...",C6,CF33F8-E6oudUQ46HnavjQ
6,"Sporting Goods, Fashion, Shoe Stores, Shopping...",C7,n_0UpQx1hsNbnPUSlodU8w
7,"Synagogues, Religious Organizations",C8,qkRM_2X51Yqxk3btlwAQIg
8,"Pubs, Restaurants, Italian, Bars, American (Tr...",C9,k0hlBqXX-Bt0vf1op7Jr1w
9,"Ice Cream & Frozen Yogurt, Fast Food, Burgers,...",C10,bBDDEgkFA1Otx9Lfe7BZUQ
10,"Department Stores, Shopping, Fashion",C11,UJsufbvfyfONHeWdvAHKjA
11,"Vietnamese, Food, Restaurants, Food Trucks",C12,eEOYSgkmpB90uNA7lDOMRA
12,"American (Traditional), Restaurants, Diners, B...",C13,il_Ro8jwPlHresjw9EGmBg
13,"General Dentistry, Dentists, Health & Medical,...",C14,jaxMSoInw8Poo3XeMJt8lQ
14,"Food, Delis, Italian, Bakeries, Restaurants",C15,0bPLkL0QhhPO5kt1_EXmNQ
15,"Sushi Bars, Restaurants, Japanese",C16,MUTTqe8uqyMdBl186RmNeA
16,"Automotive, Auto Parts & Supplies, Auto Custom...",C17,rBmpy_Y1UbBx8ggHlyb7hA
17,"Vape Shops, Tobacco Shops, Personal Shopping, ...",C18,M0XSSHqrASOnhgbWDJIpQA
18,"Automotive, Car Rental, Hotels & Travel, Truck...",C19,8wGISYjYkE2tSqn3cDMu8A
19,"Korean, Restaurants",C20,ROeacJQwBeh05Rqg7F6TCg

In [ ]:
attributes_series = business['attributes']
attributes = pd.DataFrame({'attribute': attributes_series.values})
def extract_attributes(value):
    if isinstance(value, str):
        return {value: 'True'}
    elif isinstance(value, dict):
        return value
    else:
        return None
#attributes['attribute'] = attributes['attribute'].apply(extract_attributes)
#attributes = pd.concat([attributes.drop(['attribute'], axis=1), attributes['attribute'].apply(pd.Series)], axis=1)
attributes['A_id'] = ['A{}'.format(i) for i in range(1, len(attributes) + 1)]
attributes['business_name'] = business['name']
attributes['business_id'] = business['business_id']
attributes.head()

,attribute,A_id,business_name,business_id
0,{'ByAppointmentOnly': 'True'},A1,"Abby Rappoport, LAC, CMQ",Pns2l4eNsfO8kk83dixA6A
1,{'BusinessAcceptsCreditCards': 'True'},A2,The UPS Store,mpf3x-BjTdTEA3yCZrAYPw
2,"{'BikeParking': 'True', 'BusinessAcceptsCredit...",A3,Target,tUFrWirKiKi_TAnsVWINQQ
3,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...",A4,St Honore Pastries,MTSW4McQd7CbVtyjqoe9mw
4,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...",A5,Perkiomen Valley Brewery,mWMc6_wTdE0EUBKIGXDVfA

In [ ]:
hours_series = business['hours']
hours = pd.DataFrame()
hours['business_id'] = business['business_id']
days = []
for i, row in enumerate(hours_series):
    if row is not None and isinstance(row, dict):
        for day, time_range in row.items():
            days.append({'day': day, 'time_range': time_range, 'business_id': business['business_id'][i]})
hours = pd.DataFrame(days)
hours['H_id'] = ['H{}'.format(i) for i in range(1, len(hours) + 1)]
hours.head(20)

          day time_range             business_id H_id
0      Monday    0:0-0:0  mpf3x-BjTdTEA3yCZrAYPw   H1
1     Tuesday  8:0-18:30  mpf3x-BjTdTEA3yCZrAYPw   H2
2   Wednesday  8:0-18:30  mpf3x-BjTdTEA3yCZrAYPw   H3
3    Thursday  8:0-18:30  mpf3x-BjTdTEA3yCZrAYPw   H4
4      Friday  8:0-18:30  mpf3x-BjTdTEA3yCZrAYPw   H5
5    Saturday   8:0-14:0  mpf3x-BjTdTEA3yCZrAYPw   H6
6      Monday   8:0-22:0  tUFrWirKiKi_TAnsVWINQQ   H7
7     Tuesday   8:0-22:0  tUFrWirKiKi_TAnsVWINQQ   H8
8   Wednesday   8:0-22:0  tUFrWirKiKi_TAnsVWINQQ   H9
9    Thursday   8:0-22:0  tUFrWirKiKi_TAnsVWINQQ  H10
10     Friday   8:0-23:0  tUFrWirKiKi_TAnsVWINQQ  H11
11   Saturday   8:0-23:0  tUFrWirKiKi_TAnsVWINQQ  H12
12     Sunday   8:0-22:0  tUFrWirKiKi_TAnsVWINQQ  H13
13     Monday   7:0-20:0  MTSW4McQd7CbVtyjqoe9mw  H14
14    Tuesday   7:0-20:0  MTSW4McQd7CbVtyjqoe9mw  H15
15  Wednesday   7:0-20:0  MTSW4McQd7CbVtyjqoe9mw  H16
16   Thursday   7:0-20:0  MTSW4McQd7CbVtyjqoe9mw  H17
17     Friday   7:0-21:0  MTSW4McQd7CbVtyjqoe9mw  H18
18   Saturday   7:0-21:0  MTSW4McQd7CbVtyjqoe9mw  H19
19     Sunday   7:0-21:0  MTSW4McQd7CbVtyjqoe9mw  H20

In [ ]:
#dropping attributes, categories, hours from business
business.drop(columns = ['hours','attributes','categories'],axis = 1,inplace = True)

**Creating a separate entity for 'friends', 'elite' and 'compliment' data from 'user'**

In [ ]:
friends_series = user['friends']
friends = pd.DataFrame({'friends': friends_series.values})
friends['friends'] = friends['friends'].astype(str).str.split(',')
friends = friends.explode('friends')
friends['F_id'] = ['F{}'.format(i) for i in range(1, len(friends) + 1)]
friends['user_id'] = user['user_id']

friends.head(20)

In [ ]:
elite_series = user['elite']
elite = pd.DataFrame({'elite': elite_series.values})
elite['elite'] = elite['elite'].astype(str).str.split(',')
elite = elite.explode('elite')
elite['E_id'] = ['E{}'.format(i) for i in range(1, len(elite) + 1)]
elite['user_id'] = user['user_id'].iloc[0]

elite.head(20)

  elite E_id                 user_id
0  2007   E1  qVc8ODYU5SZjKXVBgXdI7w
1  2009   E2  qVc8ODYU5SZjKXVBgXdI7w
1  2010   E3  qVc8ODYU5SZjKXVBgXdI7w
1  2011   E4  qVc8ODYU5SZjKXVBgXdI7w
1  2012   E5  qVc8ODYU5SZjKXVBgXdI7w
1  2013   E6  qVc8ODYU5SZjKXVBgXdI7w
1  2014   E7  qVc8ODYU5SZjKXVBgXdI7w
1  2015   E8  qVc8ODYU5SZjKXVBgXdI7w
1  2016   E9  qVc8ODYU5SZjKXVBgXdI7w
1  2017  E10  qVc8ODYU5SZjKXVBgXdI7w
1  2018  E11  qVc8ODYU5SZjKXVBgXdI7w
1  2019  E12  qVc8ODYU5SZjKXVBgXdI7w
1    20  E13  qVc8ODYU5SZjKXVBgXdI7w
1    20  E14  qVc8ODYU5SZjKXVBgXdI7w
1  2021  E15  qVc8ODYU5SZjKXVBgXdI7w
2  2009  E16  qVc8ODYU5SZjKXVBgXdI7w
2  2010  E17  qVc8ODYU5SZjKXVBgXdI7w
2  2011  E18  qVc8ODYU5SZjKXVBgXdI7w
2  2012  E19  qVc8ODYU5SZjKXVBgXdI7w
2  2013  E20  qVc8ODYU5SZjKXVBgXdI7w

In [ ]:
# Extract the compliment fields
compliments = ['compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list',
               'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos']

# Create a DataFrame for compliments
compliment_df = user[['user_id'] + compliments]

# Generate unique compliment IDs
compliment_df['C_id'] = ['C{}'.format(i) for i in range(1, len(compliment_df) + 1)]

# Reorder columns if needed
compliment_df = compliment_df[['C_id', 'user_id'] + compliments]

compliment_df.head(20)

<ipython-input-9-30e4eba1ec9a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  compliment_df['C_id'] = ['C{}'.format(i) for i in range(1, len(compliment_df) + 1)]

,C_id,user_id,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,C1,qVc8ODYU5SZjKXVBgXdI7w,250,65,55,56,18,232,844,467,467,239,180
1,C2,j14WgRoU_-2ZE1aw1dXrJg,1145,264,184,157,251,1847,7054,3131,3131,1521,1946
2,C3,2WnXYQFK0hXEoTxPtV2zvg,89,13,10,17,3,66,96,119,119,35,18
3,C4,SZDeASXq7o05mMNLshsdIA,24,4,1,6,2,12,16,26,26,10,9
4,C5,hA5lMy-EnncsH4JoR-hFGQ,1,1,0,0,0,1,1,0,0,0,0
5,C6,q_QQ5kBBwlCcbL1s4NVK3g,1713,163,191,361,147,1212,5696,2543,2543,815,323
6,C7,cxuxXkcihfCbqt5Byrup8Q,0,0,0,0,0,0,1,0,0,0,0
7,C8,E9kcWJdJUHuTKfQurPljwA,4,7,2,0,0,8,6,12,12,5,0
8,C9,lO1iq-f75hnPNZkTy3Zerg,2,0,0,3,0,3,4,5,5,3,1
9,C10,AUi8MPWJ0mLkMfwbui27lg,0,0,0,0,0,1,6,3,3,0,0
10,C11,iYzhPPqnrjJkg1JHZyMhzA,0,0,0,0,0,0,0,0,0,0,0
11,C12,xoZvMJPDW6Q9pDAXI0e_Ww,23,9,1,3,5,31,41,36,36,24,7
12,C13,vVukUtqoLF5BvH_VtQFNoA,4,0,0,0,0,1,5,0,0,1,0
13,C14,_crIokUeTCHVK_JVOy-0qQ,0,0,0,0,0,0,0,0,0,0,0
14,C15,1McG5Rn_UDkmlkZOrsdptg,1,0,0,0,0,1,0,2,2,0,0
15,C16,SgiBkhXeqIKl1PlFpZOycQ,212,17,17,22,34,67,158,221,221,45,17
16,C17,fJZO_skqpnhk1kvomI4dmA,0,1,0,0,0,6,2,2,2,1,0
17,C18,x7YtLnBW2dUnrrpwaofVQQ,15,1,0,0,0,12,33,66,66,1,12
18,C19,QF1Kuhs8iwLWANNZxebTow,1020,79,68,29,23,144,407,808,808,587,723
19,C20,VcLRGCG_VbAo8MxOm76jzA,1,0,0,0,0,2,4,0,0,1,0

In [ ]:
#dropping friends, elite, compliments from user
user.drop(columns = ['friends','elite', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list',
               'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos'],axis = 1,inplace = True)

#  **Installing SQL Packages**

In [ ]:
from sqlalchemy import create_engine
!pip install PyMySql
import pymysql
import sqlalchemy

Collecting PyMySql
  Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.2 MB/s eta 0:00:00
Installing collected packages: PyMySql
Successfully installed PyMySql-1.1.0

#### Setting the password

In [ ]:
# !pip install mysql-connector-python
# import mysql.connector
# group_name = 'B10'
# conn = mysql.connector.connect(
#     host="testproject.mysql.database.azure.com",
#     user=group_name,
#     # Assuming password is group_name followed by "password" (e.g., "A01password")
#     password=f"B10@Gies",
#     # Using the database corresponding to the group name.
#     database=group_name
# )

# # Create a cursor object to interact with the database.
# cursor = conn.cursor()

# # Define the new password that you want to set.
# new_password = "B10Gies"

# # Execute the SQL command to alter the user's password.
# cursor.execute(f"ALTER USER '{group_name}'@'%' IDENTIFIED BY '{new_password}';")

# # Commit the changes to the database.
# conn.commit()

# # Close the cursor and the database connection.
# cursor.close()
# conn.close()

#### Setting up connection

In [ ]:
pip install mysqlclient

Collecting mysqlclient
  Downloading mysqlclient-2.2.0.tar.gz (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 kB 1.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (pyproject.toml) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.2.0-cp310-cp310-linux_x86_64.whl size=123670 sha256=bde8e20f13195b38ca49b7def56468b69060541860b621c505a6a8e243394c9b
  Stored in directory: /root/.cache/pip/wheels/a4/f8/fd/0399687c0abd03c10c975ed56c692fcd3d0fb80440b5a661f1
Successfully built mysqlclient
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.2.0

In [ ]:
%load_ext sql
%sql mysql://B10:B10Gies@testproject.mysql.database.azure.com:3306/B10

In [ ]:
connection_string = f"mysql+pymysql://B10:B10Gies@testproject.mysql.database.azure.com:3306/B10"
#mysql://B10:B10Gies@testproject.mysql.database.azure.com:3306/B10

# **Moving the data to azure**

In [ ]:
review.to_sql(con=connection_string, name='review',if_exists='replace',chunksize=50000)

6990280

In [ ]:
business.to_sql(con=connection_string, name='business',if_exists='replace',chunksize=2500)

150346

In [ ]:
checkin.to_sql(con=connection_string, name='checkin',if_exists='replace',chunksize=50000)

13356875

In [ ]:
attributes.to_sql(con=connection_string, name='attributes',if_exists='replace',   dtype={'attribute': sqlalchemy.types.JSON}, chunksize=50000)

150346

In [ ]:
hours.to_sql(con=connection_string, name='hours',if_exists='replace', chunksize=50000)

801015

In [ ]:
categories.to_sql(con=connection_string, name='categories',if_exists='replace',  dtype={'category': sqlalchemy.types.JSON}, chunksize=50000)

150346

In [ ]:
friends.to_sql(con=connection_string, name='friends',if_exists='replace', chunksize=50000)

2889998

In [ ]:
tip.to_sql(con=connection_string, name='tip',if_exists='replace', chunksize=50000)

908915

In [ ]:
elite.to_sql(con=connection_string, name='elite',if_exists='replace', chunksize=50000)

2277195

In [ ]:
compliment_df.to_sql(con=connection_string, name='compliments',if_exists='replace', chunksize=50000)

1987897

In [ ]:
user.to_sql(con=connection_string, name='user',if_exists='replace', chunksize=50000)

1987897

Testing tables

In [ ]:
%%sql
select count(*) from business;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
1 rows affected.

[(150346,)]

In [ ]:
%%sql
select count(*) from review;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10

**Adding primary keys to the tables**

In [ ]:
%%sql
SHOW KEYS FROM business WHERE Key_name = 'PRIMARY'

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
1 rows affected.

[('business', 0, 'PRIMARY', 1, 'business_id', 'A', 0, None, None, '', 'BTREE', '', '', 'YES', None)]

In [ ]:
%%sql
USE B10;
ALTER TABLE business
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN C_id business_id(100) NOT NULL,
ADD PRIMARY KEY(business_id);

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
0 rows affected.
(MySQLdb.OperationalError) (1091, "Can't DROP 'my_row_id'; check that column/key exists")
[SQL: ALTER TABLE business
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
ADD PRIMARY KEY(business_id);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

See error as business id is already a PK.

In [ ]:
%%sql
USE B10;
ALTER TABLE review
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN review_id varchar(100) NOT NULL,
ADD PRIMARY KEY(review_id);

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
0 rows affected.
6990280 rows affected.

[]

In [ ]:
%%sql
USE B10;
ALTER TABLE user
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN user_id varchar(100) NOT NULL,
ADD PRIMARY KEY(user_id);

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
0 rows affected.
(MySQLdb.OperationalError) (1170, "BLOB/TEXT column 'user_id' used in key specification without a key length")
[SQL: ALTER TABLE user
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
ADD PRIMARY KEY(user_id);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
%%sql
USE B10;
ALTER TABLE attributes
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN A_id varchar(100) NOT NULL,
ADD PRIMARY KEY(A_id);

In [ ]:
%%sql
USE B10;
ALTER TABLE hours
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN H_id varchar(100) NOT NULL,
ADD PRIMARY KEY(H_id);

In [ ]:
%%sql
USE B10;
ALTER TABLE categories
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN C_id varchar(100) NOT NULL,
ADD PRIMARY KEY(C_id);

In [ ]:
%%sql
USE B10;
ALTER TABLE elite
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN E_id varchar(100) NOT NULL,
ADD PRIMARY KEY(E_id);

In [ ]:
%%sql
USE B10;
ALTER TABLE friend
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY COLUMN F_id varchar(100) NOT NULL,
ADD PRIMARY KEY(F_id);

# **SQL queries to set up a new restaurant**

In [ ]:
%%sql
#1. Find the top 10 cities with the maximum number of restaurants in state. This query can help comprehend the original restaurant market in each city and state.
SELECT  state, city,count(b.business_id) AS num_bus
FROM business b join categories c on b.business_id = c.business_id
and category like '%Restaurants%'
GROUP BY  state,city
ORDER BY num_bus DESC
limit 10;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
10 rows affected.

[('PA', 'Philadelphia', 5854),
 ('FL', 'Tampa', 2967),
 ('IN', 'Indianapolis', 2862),
 ('TN', 'Nashville', 2504),
 ('AZ', 'Tucson', 2469),
 ('LA', 'New Orleans', 2261),
 ('AB', 'Edmonton', 2168),
 ('MO', 'Saint Louis', 1790),
 ('NV', 'Reno', 1288),
 ('ID', 'Boise', 848)]

Philadelphia has the most restuarants. Therefore, we will focus only on that city.

In [ ]:
%%sql
#2. Find the category of restaurants with the highest stars in different cities.
select name, category,stars
from business b join categories c on b.business_id = c.business_id
where category LIKE "%Restaurants%"
and city in ("Philadelphia")
ORDER BY stars DESC
limit 15;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
15 rows affected.

[('The Black Cat Tavern On 12th', '"Beer Bar, Dive Bars, Gastropubs, Cocktail Bars, Nightlife, Bars, Restaurants"', 5.0),
 ('K & A Sandwiches & Grocery', '"Restaurants, Grocery, Sandwiches, Convenience Stores, Food"', 5.0),
 ('Villari Brothers Bakery', '"Bakeries, Pizza, Restaurants, Italian, Food"', 5.0),
 ('Restaurant Ambra', '"Italian, Restaurants"', 5.0),
 ("Li'l Nick's Deli", '"Restaurants, Delis"', 5.0),
 ('Meatheads Deli', '"Restaurants, Delis, Sandwiches"', 5.0),
 ('Belgrade Deli', '"Convenience Stores, Grocery, Food, Restaurants, Sandwiches, Delis"', 5.0),
 ('Fruit Salad Truck', '"Restaurants, Food Stands"', 5.0),
 ("Dimitrio & Frida's Food Cart", '"Restaurants, Food Trucks, Food Stands, Food, Sandwiches"', 5.0),
 ("Dew's Deli", '"Restaurants, Delis"', 5.0),
 ('El Bocado', '"Restaurants, Mexican, Latin American, Salvadoran, Honduran"', 5.0),
 ("McNally's Tavern - Mayfair", '"American (Traditional), Nightlife, Pubs, Restaurants, Bars"', 5.0),
 ('Cafe Mai Vy', '"Vietnamese, Restaurants"', 5.0),
 ('Malooga', '"Seafood, Mediterranean, Breakfast & Brunch, Hookah Bars, Salad, Arabic, Chicken Shop, Restaurants, Nightlife, Bars"', 5.0),
 ('Rico Mexican Tacos', '"Mexican, Restaurants"', 5.0)]

Pizzas and Delis receive high stars frequently.

In [ ]:
%%sql
#3. Finding most reviewed categories of restaurants
select sum(review_count) as total_reviews, name,category
from business b join categories c on b.business_id = c.business_id
where category LIKE "%Restaurant%"
and city in ("Philadelphia")
group by 2,3
order by 1 desc
limit 15;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
15 rows affected.

[(Decimal('5721'), 'Reading Terminal Market', '"Candy Stores, Shopping, Department Stores, Fast Food, Beer, Wine & Spirits, Fruits & Veggies, Chinese, Food, Ice Cream & Frozen Yogurt, Desserts, Se ... (207 characters truncated) ... ment, Juice Bars & Smoothies, Seafood Markets, Farmers Market, Coffee & Tea, Bakeries, Food Stands, Dinner Theater, Sporting Goods, Grocery, Fashion"'),
 (Decimal('4250'), "Pat's King of Steaks", '"Italian, American (Traditional), Sandwiches, Fast Food, Restaurants, Local Flavor, Cheesesteaks"'),
 (Decimal('3531'), 'Green Eggs Café', '"Restaurants, American (New), Diners, Breakfast & Brunch"'),
 (Decimal('3401'), "Geno's Steaks", '"Sandwiches, Cheesesteaks, Steakhouses, Restaurants"'),
 (Decimal('3187'), 'El Vez', '"Lounges, Bars, Nightlife, Breakfast & Brunch, Mexican, Restaurants"'),
 (Decimal('3065'), 'Zahav', '"Nightlife, Bars, Food, Ethnic Food, Middle Eastern, Vegetarian, Specialty Food, Israeli, Restaurants"'),
 (Decimal('2893'), 'Barbuzzo', '"Mediterranean, Restaurants, Pizza, Italian"'),
 (Decimal('2761'), 'Parc', '"Restaurants, French, Wine Bars, Nightlife, American (New), Bars, Cafes, Breakfast & Brunch"'),
 (Decimal('2736'), "Jim's South St", '"Bars, Restaurants, Pizza, Cheesesteaks, Italian, Beer Bar, American (Traditional), Local Flavor, Nightlife, Sandwiches"'),
 (Decimal('2686'), 'Dalessandro’s Steaks & Hoagies', '"Sandwiches, Delis, Restaurants, Cheesesteaks"'),
 (Decimal('2672'), 'Dim Sum Garden', '"Chinese, Restaurants, Dim Sum, Asian Fusion, Shanghainese"'),
 (Decimal('2497'), 'The Dandelion', '"British, Restaurants, Gastropubs, Bars, Nightlife"'),
 (Decimal('2221'), "Tommy DiNic's", '"Restaurants, American (Traditional), Sandwiches"'),
 (Decimal('2188'), 'Nan Zhou Hand Drawn Noodle House', '"Specialty Food, Noodles, Ethnic Food, Chinese, Comfort Food, Restaurants, Food"'),
 (Decimal('2184'), "Monk's Cafe", '"Nightlife, Pubs, Bars, Belgian, Restaurants, Gastropubs"')]

In [ ]:
%%sql
#4. Seems like Pizza and Delis  are pretty highly rated and fall in top 10 most reviewed. Find total such restaurants.
select count(distinct category) as total_restaurants, SUM(case when category LIKE "%Delis%"  then 1 else 0 end)  as total_delis,
SUM(case when category LIKE "%Pizza%"  then 1 else 0 end)  as total_pizza
from business b join categories c on b.business_id = c.business_id
where category LIKE "%Restaurants%"
and city in ("Philadelphia")
ORDER BY 1 DESC
limit 15;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
1 rows affected.

[(4325, Decimal('308'), Decimal('800'))]

#### Delis are fewer compared to pizza places but are pretty highly rated, hence, we will open a deli restaurant

In [ ]:
%%sql
#5. find place in PA where people go the most (after "2022-01-01")
select count(distinct ch.business_id) as total_checkins,b.postal_code
from
business b join checkin ch
on
b.business_id = ch.business_id
join categories c on b.business_id = c.business_id
where category LIKE "%Restaurants%"
and city in ("Philadelphia")
and date(ch.date) > "2022-01-01"
group by 2
ORDER BY 1 DESC
limit 15;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
15 rows affected.

[(99, '19107'),
 (65, '19147'),
 (56, '19103'),
 (40, '19106'),
 (28, '19148'),
 (27, '19123'),
 (23, '19125'),
 (23, '19104'),
 (21, '19130'),
 (20, '19102'),
 (13, '19127'),
 (13, '19128'),
 (12, '19146'),
 (12, '19145'),
 (11, '19122')]

Most checkins have happened in the area: 19107 and hence, we will go ahead and open a deli within the same area.

In [ ]:
%%sql
#6. Finding the attributes of most tipped deli in the area
select attribute,count(distinct t.business_id	) as total_tips
from
business b join attributes a
on
b.business_id = a.business_id
join tip t on b.business_id = t.business_id
join categories c on b.business_id = c.business_id
where category LIKE "%Restaurants%"
and city in ("Philadelphia")
and  category LIKE "%Delis%"
and postal_code = 19107
group by 1
ORDER BY 1 DESC
limit 15;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
15 rows affected.

[('{"BYOB": "False", "WiFi": "u\'free\'", "HasTV": "True", "Caters": "False", "Alcohol": "u\'none\'", "Corkage": "False", "Ambience": "{\'romantic\': Fa ... (719 characters truncated) ... 1", "RestaurantsReservations": "False", "RestaurantsTableService": "True", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'touristy\': False, \'hipster\': False, \'romantic\' ... (683 characters truncated) ... ", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "\'no\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'classy\': Fa ... (678 characters truncated) ... 1", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "True", "Caters": "False", "Alcohol": "\'none\'", "Ambience": "{\'touristy\': False, \'hipster\': False, \'romantic\': ... (654 characters truncated) ... ", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"BYOB": "False", "WiFi": "u\'no\'", "HasTV": "False", "Caters": "False", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': Fa ... (517 characters truncated) ... ", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'classy\': ... (636 characters truncated) ... 1", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'touristy\ ... (592 characters truncated) ...  "True", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'no\'", "HasTV": "True", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'touristy\': False, \'hipster\': False, \'romantic\': F ... (609 characters truncated) ... ", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'no\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'touristy\': ... (572 characters truncated) ... False", "RestaurantsPriceRange2": "2", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'no\'", "HasTV": "False", "Caters": "False", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'classy\':  ... (435 characters truncated) ... False", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"Caters": "True", "Alcohol": "u\'beer_and_wine\'", "Smoking": "u\'outdoor\'", "Ambience": "{\'touristy\': False, \'hipster\': False, \'romantic\': F ... (557 characters truncated) ...  "True", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "True", "Caters": "False", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'classy\': ... (437 characters truncated) ... False", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'no\'", "HasTV": "True", "Caters": "False", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'classy\': F ... (430 characters truncated) ...  "True", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'no\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'beer_and_wine\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'cl ... (447 characters truncated) ... False", "RestaurantsPriceRange2": "2", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"WiFi": "u\'free\'", "HasTV": "False", "Caters": "True", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': False, \'touristy\ ... (433 characters truncated) ... "False", "RestaurantsPriceRange2": "1", "RestaurantsReservations": "False", "RestaurantsGoodForGroups": "True", "BusinessAcceptsCreditCards": "True"}', 1)]

Seems like casual delis are the most highly tipped. We want to understand if it is an acceptable business model to not allow BYOB

In [ ]:
#.7  Finding total deli where BYOB is False
%%sql
select attribute,count(distinct t.business_id	) as total_tips
from
business b join attributes a
on
b.business_id = a.business_id
join tip t on b.business_id = t.business_id
join categories c on b.business_id = c.business_id
where category LIKE "%Restaurants%"
and city in ("Philadelphia")
and  category LIKE "%Delis%"
and postal_code = 19107
and JSON_EXTRACT(attribute, "$.BYOB") = "False"
group by 1
ORDER BY 1 DESC
limit 10;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
2 rows affected.

[('{"BYOB": "False", "WiFi": "u\'free\'", "HasTV": "True", "Caters": "False", "Alcohol": "u\'none\'", "Corkage": "False", "Ambience": "{\'romantic\': Fa ... (719 characters truncated) ... 1", "RestaurantsReservations": "False", "RestaurantsTableService": "True", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1),
 ('{"BYOB": "False", "WiFi": "u\'no\'", "HasTV": "False", "Caters": "False", "Alcohol": "u\'none\'", "Ambience": "{\'romantic\': False, \'intimate\': Fa ... (517 characters truncated) ... ", "RestaurantsReservations": "False", "RestaurantsTableService": "False", "RestaurantsGoodForGroups": "False", "BusinessAcceptsCreditCards": "True"}', 1)]

We can use similar attributes for our restaurant.

In [ ]:
#Query 8 Finding the most common hours of operations for  delis
%%sql
select time_range, count(*)
from business b  join categories c on b.business_id = c.business_id
join hours h on h.business_id = b.business_id
where category LIKE "%Restaurant%"
and city in ("Philadelphia")
and  category LIKE "%Delis%"
group by 1
order by 2 desc
limit 10;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
10 rows affected.

[('0:0-0:0', 134),
 ('7:0-19:0', 70),
 ('7:0-22:0', 56),
 ('9:0-16:0', 53),
 ('7:0-16:0', 50),
 ('8:0-19:0', 50),
 ('7:0-21:0', 47),
 ('6:0-23:0', 44),
 ('10:0-22:0', 41),
 ('8:0-21:0', 38)]

Our restaurant can operate between the standard hours of 7 am to 10pm

In [ ]:
#Query 9 Finding reviews about deli restuarants to take recommendations from low rated restaurants
%%sql
select text from review where (text like '%deli %' or text like '%Deli %') and stars < 4
limit 5;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
5 rows affected.

[('Worst Wawa in the Tri-State area. Always full of druggies, weirdos, creeps, panhandlers and the worst deli staff ever.',),
 ("This is a great place to visit if you enjoy large crowds and overspending.\n\nThey have plenty of delicious deli and bakery items available but you g ... (375 characters truncated) ... ry full of people, so if you're the type of person who is not into that sort of thing, I would probably try to go in the most non-peak hours you can.",),
 ('The guys in the deli are slow! All they do is talk and look around trying to avoid work. If you buy produce there eat it fast it does not stay fresh very long',),
 ('Slllooowweeessttt deli counter ever! Been waiting for over 20 minutes for the Daily Special of all things. I could have caught the fish myself in this amount of time.',),
 ("I'm in no way a pho pro, but I liked Saigon Deli better than this one, but those who are looking for Pho, that place is not open in the evenings, at  ... (403 characters truncated) ... king about the other place. The flavor, the sizes for the price, and the service at the other place was much better than my experience at Pho An Hoa.",)]

It looks like reviewers are particularly upset about slow service in delis. We need to make sure we correct that in our business

In [ ]:
#Query 10 Finding influencers for marketing
%%sql
select user_id,sum(useful) as most_useful, sum(fans) as total_fans, sum(review_count) as total_reviews from user
group by 1
order by 2 desc,4 desc, 3 desc limit 20;

 * mysql://B10:***@testproject.mysql.database.azure.com:3306/B10
20 rows affected.

[('Hi10sGSZNxQH3NLyWSZ1oA', Decimal('206296'), Decimal('3493'), Decimal('17473')),
 ('--2vR0DIsmQ6WfcSzKWigw', Decimal('205765'), Decimal('880'), Decimal('1534')),
 ('JjXuiru1_ONzDkYVrHN0aw', Decimal('183512'), Decimal('3243'), Decimal('1424')),
 ('lvthTfCQGD0qaEk6jCdRdQ', Decimal('182788'), Decimal('808'), Decimal('2960')),
 ('hWDybu_KvYLSdEFzGrniTw', Decimal('173089'), Decimal('867'), Decimal('16567')),
 ('8k3aO-mPeyhbR5HUucA5aA', Decimal('152979'), Decimal('1462'), Decimal('16978')),
 ('Kf5PVQUdDvQYf-MXoeWqZA', Decimal('142453'), Decimal('1021'), Decimal('2702')),
 ('AbMjnKOwg736fcIu8apuyQ', Decimal('124311'), Decimal('1563'), Decimal('3133')),
 ('7W-p-PJlmrzg0mk3pWKoyQ', Decimal('117066'), Decimal('597'), Decimal('765')),
 ('ax7SnXOTIpatbsmqHLqVow', Decimal('112557'), Decimal('605'), Decimal('972')),
 ('Ggx8iUdJ7lsQSqXRuclXtg', Decimal('110553'), Decimal('850'), Decimal('3499')),
 ('Hm0diOkWwpo9zotlJlqMUQ', Decimal('106525'), Decimal('634'), Decimal('2481')),
 ('YTu0c-1I9ECeksIgoHXFPA', Decimal('104404'), Decimal('558'), Decimal('2228')),
 ('W7DHyQlY_kXls2iXt-_2Ag', Decimal('100480'), Decimal('1179'), Decimal('3028')),
 ('eeErZzgWenz9ck7FGdFUfw', Decimal('86602'), Decimal('173'), Decimal('1856')),
 ('0H2ggT37lK8hsbH8aGR1Ug', Decimal('81095'), Decimal('830'), Decimal('1311')),
 ('_cpU0VVdQcfN5AnuL6M56A', Decimal('80394'), Decimal('347'), Decimal('1295')),
 ('zFYs8gSUYDvXkb6O7YkRkw', Decimal('77980'), Decimal('1662'), Decimal('1082')),
 ('a4mO387_O77ebmv8AlQB3A', Decimal('76505'), Decimal('539'), Decimal('3362')),
 ('gqL5KBs2oS7qobnyd99iKg', Decimal('75097'), Decimal('728'), Decimal('2645'))]

Users with ids Hi10sGSZNxQH3NLyWSZ1oA and 2vR0DIsmQ6WfcSzKWigw appear to be influencers. We can invite them to review the restaurant at the opening as a marketing strategy.